/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SetupPasswordRouteImport } from './routes/setup-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as UnavailableRouteImport } from './routes/unavailable'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdministrationRouteImport } from './routes/_authenticated/administration'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAdministrationBookingTypesRouteImport } from './routes/_authenticated/administration.booking-types'
import { Route as AuthenticatedAdministrationGroupsRouteImport } from './routes/_authenticated/administration.groups'
import { Route as AuthenticatedAdministrationGroupsIndexRouteImport } from './routes/_authenticated/administration.groups.index'
import { Route as AuthenticatedAdministrationGroupsNewRouteImport } from './routes/_authenticated/administration.groups.new'
import { Route as AuthenticatedAdministrationGroupsGroupIdEditRouteImport } from './routes/_authenticated/administration.groups.$groupId.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupPasswordRoute = SetupPasswordRouteImport.update({
  id: '/setup-password',
  path: '/setup-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const UnavailableRoute = UnavailableRouteImport.update({
  id: '/unavailable',
  path: '/unavailable',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdministrationRoute =
  AuthenticatedAdministrationRouteImport.update({
    id: '/administration',
    path: '/administration',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdministrationBookingTypesRoute =
  AuthenticatedAdministrationBookingTypesRouteImport.update({
    id: '/booking-types',
    path: '/booking-types',
    getParentRoute: () => AuthenticatedAdministrationRoute,
  } as any)
const AuthenticatedAdministrationGroupsRoute =
  AuthenticatedAdministrationGroupsRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => AuthenticatedAdministrationRoute,
  } as any)
const AuthenticatedAdministrationGroupsIndexRoute =
  AuthenticatedAdministrationGroupsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdministrationGroupsRoute,
  } as any)
const AuthenticatedAdministrationGroupsNewRoute =
  AuthenticatedAdministrationGroupsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdministrationGroupsRoute,
  } as any)
const AuthenticatedAdministrationGroupsGroupIdEditRoute =
  AuthenticatedAdministrationGroupsGroupIdEditRouteImport.update({
    id: '/$groupId/edit',
    path: '/$groupId/edit',
    getParentRoute: () => AuthenticatedAdministrationGroupsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/setup': typeof SetupRoute
  '/setup-password': typeof SetupPasswordRoute
  '/sign-in': typeof SignInRoute
  '/unavailable': typeof UnavailableRoute
  '/administration': typeof AuthenticatedAdministrationRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/administration/booking-types': typeof AuthenticatedAdministrationBookingTypesRoute
  '/administration/groups': typeof AuthenticatedAdministrationGroupsRouteWithChildren
  '/administration/groups/new': typeof AuthenticatedAdministrationGroupsNewRoute
  '/administration/groups/': typeof AuthenticatedAdministrationGroupsIndexRoute
  '/administration/groups/$groupId/edit': typeof AuthenticatedAdministrationGroupsGroupIdEditRoute
}
export interface FileRoutesByTo {
  '/setup': typeof SetupRoute
  '/setup-password': typeof SetupPasswordRoute
  '/sign-in': typeof SignInRoute
  '/unavailable': typeof UnavailableRoute
  '/administration': typeof AuthenticatedAdministrationRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/': typeof AuthenticatedIndexRoute
  '/administration/booking-types': typeof AuthenticatedAdministrationBookingTypesRoute
  '/administration/groups/new': typeof AuthenticatedAdministrationGroupsNewRoute
  '/administration/groups': typeof AuthenticatedAdministrationGroupsIndexRoute
  '/administration/groups/$groupId/edit': typeof AuthenticatedAdministrationGroupsGroupIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/setup': typeof SetupRoute
  '/setup-password': typeof SetupPasswordRoute
  '/sign-in': typeof SignInRoute
  '/unavailable': typeof UnavailableRoute
  '/_authenticated/administration': typeof AuthenticatedAdministrationRouteWithChildren
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/administration/booking-types': typeof AuthenticatedAdministrationBookingTypesRoute
  '/_authenticated/administration/groups': typeof AuthenticatedAdministrationGroupsRouteWithChildren
  '/_authenticated/administration/groups/new': typeof AuthenticatedAdministrationGroupsNewRoute
  '/_authenticated/administration/groups/': typeof AuthenticatedAdministrationGroupsIndexRoute
  '/_authenticated/administration/groups/$groupId/edit': typeof AuthenticatedAdministrationGroupsGroupIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/setup-password'
    | '/sign-in'
    | '/unavailable'
    | '/administration'
    | '/calendar'
    | '/administration/booking-types'
    | '/administration/groups'
    | '/administration/groups/new'
    | '/administration/groups/'
    | '/administration/groups/$groupId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/setup'
    | '/setup-password'
    | '/sign-in'
    | '/unavailable'
    | '/administration'
    | '/calendar'
    | '/'
    | '/administration/booking-types'
    | '/administration/groups/new'
    | '/administration/groups'
    | '/administration/groups/$groupId/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/setup'
    | '/setup-password'
    | '/sign-in'
    | '/unavailable'
    | '/_authenticated/administration'
    | '/_authenticated/calendar'
    | '/_authenticated/'
    | '/_authenticated/administration/booking-types'
    | '/_authenticated/administration/groups'
    | '/_authenticated/administration/groups/new'
    | '/_authenticated/administration/groups/'
    | '/_authenticated/administration/groups/$groupId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SetupRoute: typeof SetupRoute
  SetupPasswordRoute: typeof SetupPasswordRoute
  SignInRoute: typeof SignInRoute
  UnavailableRoute: typeof UnavailableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-password': {
      id: '/setup-password'
      path: '/setup-password'
      fullPath: '/setup-password'
      preLoaderRoute: typeof SetupPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unavailable': {
      id: '/unavailable'
      path: '/unavailable'
      fullPath: '/unavailable'
      preLoaderRoute: typeof UnavailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administration': {
      id: '/_authenticated/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AuthenticatedAdministrationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administration/booking-types': {
      id: '/_authenticated/administration/booking-types'
      path: '/booking-types'
      fullPath: '/administration/booking-types'
      preLoaderRoute: typeof AuthenticatedAdministrationBookingTypesRouteImport
      parentRoute: typeof AuthenticatedAdministrationRoute
    }
    '/_authenticated/administration/groups': {
      id: '/_authenticated/administration/groups'
      path: '/groups'
      fullPath: '/administration/groups'
      preLoaderRoute: typeof AuthenticatedAdministrationGroupsRouteImport
      parentRoute: typeof AuthenticatedAdministrationRoute
    }
    '/_authenticated/administration/groups/': {
      id: '/_authenticated/administration/groups/'
      path: '/'
      fullPath: '/administration/groups/'
      preLoaderRoute: typeof AuthenticatedAdministrationGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedAdministrationGroupsRoute
    }
    '/_authenticated/administration/groups/new': {
      id: '/_authenticated/administration/groups/new'
      path: '/new'
      fullPath: '/administration/groups/new'
      preLoaderRoute: typeof AuthenticatedAdministrationGroupsNewRouteImport
      parentRoute: typeof AuthenticatedAdministrationGroupsRoute
    }
    '/_authenticated/administration/groups/$groupId/edit': {
      id: '/_authenticated/administration/groups/$groupId/edit'
      path: '/$groupId/edit'
      fullPath: '/administration/groups/$groupId/edit'
      preLoaderRoute: typeof AuthenticatedAdministrationGroupsGroupIdEditRouteImport
      parentRoute: typeof AuthenticatedAdministrationGroupsRoute
    }
  }
}

interface AuthenticatedAdministrationGroupsRouteChildren {
  AuthenticatedAdministrationGroupsNewRoute: typeof AuthenticatedAdministrationGroupsNewRoute
  AuthenticatedAdministrationGroupsIndexRoute: typeof AuthenticatedAdministrationGroupsIndexRoute
  AuthenticatedAdministrationGroupsGroupIdEditRoute: typeof AuthenticatedAdministrationGroupsGroupIdEditRoute
}

const AuthenticatedAdministrationGroupsRouteChildren: AuthenticatedAdministrationGroupsRouteChildren =
  {
    AuthenticatedAdministrationGroupsNewRoute:
      AuthenticatedAdministrationGroupsNewRoute,
    AuthenticatedAdministrationGroupsIndexRoute:
      AuthenticatedAdministrationGroupsIndexRoute,
    AuthenticatedAdministrationGroupsGroupIdEditRoute:
      AuthenticatedAdministrationGroupsGroupIdEditRoute,
  }

const AuthenticatedAdministrationGroupsRouteWithChildren =
  AuthenticatedAdministrationGroupsRoute._addFileChildren(
    AuthenticatedAdministrationGroupsRouteChildren,
  )

interface AuthenticatedAdministrationRouteChildren {
  AuthenticatedAdministrationBookingTypesRoute: typeof AuthenticatedAdministrationBookingTypesRoute
  AuthenticatedAdministrationGroupsRoute: typeof AuthenticatedAdministrationGroupsRouteWithChildren
}

const AuthenticatedAdministrationRouteChildren: AuthenticatedAdministrationRouteChildren =
  {
    AuthenticatedAdministrationBookingTypesRoute:
      AuthenticatedAdministrationBookingTypesRoute,
    AuthenticatedAdministrationGroupsRoute:
      AuthenticatedAdministrationGroupsRouteWithChildren,
  }

const AuthenticatedAdministrationRouteWithChildren =
  AuthenticatedAdministrationRoute._addFileChildren(
    AuthenticatedAdministrationRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdministrationRoute: typeof AuthenticatedAdministrationRouteWithChildren
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdministrationRoute:
    AuthenticatedAdministrationRouteWithChildren,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SetupRoute: SetupRoute,
  SetupPasswordRoute: SetupPasswordRoute,
  SignInRoute: SignInRoute,
  UnavailableRoute: UnavailableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
